#pragma once

//MAIN WINDOW
#define WINDOW_TITLE "Frogger"
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 680

//FROG
#define FROG_MOVEMENT_JUMP 40
#define FROG_START_POSITION_X (400, 0)
#define FROG_START_POSITION_Y (0, 600)

//CAR
#define CAR_MOVEMENT_SPEED_FAST_X 0.05
#define CAR_MOVEMENT_SPEED_SLOW_X 0.03
#define CAR_SIZE_WIDTH 60
#define CAR_SIZE_HEIGHT 40

//TRUCK
#define TRUCK_MOVEMENT_SPEED_X 0.04
#define TRUCK_SIZE_WIDTH 120
#define TRUCK_SIZE_HEIGHT 80

// HOME
#define HOME_COLOR (140, 150, 90)
#define HOME_POSITION_Y (0,0)

//LILYPADS
#define LILYPADS_COLOR (125, 230, 97)
#define LILYPADS_POSITION_Y (0,120)
#define LILYPADS_SIZE_WIDTH 80
#define LILYPADS_SIZE_HEIGHT 40

//LOGBEAMS
#define LOGBEAMS_SIZE_SMALL_WIDTH 80
#define LOGBEAMS_SIZE_SMALL_HEIGHT 40
#define LOGBEAMS_SIZE_LARGE_WIDTH 100
#define LOGBEAMS_SIZE_LARGE_HEIGHT 40
#define LOGBEAMS_MOVEMENT_SPEED_FAST_X 0.045
#define LOGBEAMS_MOVEMENT_SPEED_SLOW_X 0.025